# permissions for end users to view ipoibnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipoibnetwork-viewer-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - ipoibnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - ipoibnetworks/status
  verbs:
  - get
