# permissions for end users to edit ipoibnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipoibnetwork-editor-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - ipoibnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - ipoibnetworks/status
  verbs:
  - get
